"use client";

import { useState, useTransition } from "react";
import { AutoGeneratedBadge, DrillTypeBadge } from "@/components/ui/auto-generated-badge";
import { approveDrill, deleteDrill, updateDrillContent } from "@/lib/actions/recording-review";
import { Button } from "@/components/ui/button";

interface DrillContent {
  prompt?: string;
  target?: string;
  context?: string;
  correction?: string;
  explanation?: string;
  example?: string;
  options?: string[];
  [key: string]: unknown;
}

interface DrillPreviewCardProps {
  drill: {
    id: string;
    content: DrillContent;
    drill_type: string;
    focus_area: string | null;
    source: string;
    visible_to_student: boolean;
    tutor_approved: boolean;
  };
  onUpdate?: () => void;
}

export function DrillPreviewCard({ drill, onUpdate }: DrillPreviewCardProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState<DrillContent>(drill.content);
  const [isPending, startTransition] = useTransition();
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  const handleApprove = () => {
    startTransition(async () => {
      const result = await approveDrill(drill.id);
      if (result.success) {
        onUpdate?.();
      }
    });
  };

  const handleDelete = () => {
    startTransition(async () => {
      const result = await deleteDrill(drill.id);
      if (result.success) {
        setShowDeleteConfirm(false);
        onUpdate?.();
      }
    });
  };

  const handleSaveEdit = () => {
    startTransition(async () => {
      const result = await updateDrillContent(drill.id, editedContent);
      if (result.success) {
        setIsEditing(false);
        onUpdate?.();
      }
    });
  };

  const renderContent = () => {
    const content = isEditing ? editedContent : drill.content;

    return (
      <div className="space-y-2 text-sm">
        {content.prompt && (
          <div>
            <span className="font-medium text-gray-700">Prompt: </span>
            {isEditing ? (
              <input
                type="text"
                value={content.prompt}
                onChange={(e) => setEditedContent({ ...editedContent, prompt: e.target.value })}
                className="w-full mt-1 px-2 py-1 border border-gray-300 rounded text-sm"
              />
            ) : (
              <span className="text-gray-900">{content.prompt}</span>
            )}
          </div>
        )}

        {content.target && (
          <div>
            <span className="font-medium text-gray-700">Target: </span>
            {isEditing ? (
              <input
                type="text"
                value={content.target}
                onChange={(e) => setEditedContent({ ...editedContent, target: e.target.value })}
                className="w-full mt-1 px-2 py-1 border border-gray-300 rounded text-sm"
              />
            ) : (
              <span className="text-gray-900">{content.target}</span>
            )}
          </div>
        )}

        {content.correction && (
          <div>
            <span className="font-medium text-gray-700">Correction: </span>
            {isEditing ? (
              <input
                type="text"
                value={content.correction}
                onChange={(e) => setEditedContent({ ...editedContent, correction: e.target.value })}
                className="w-full mt-1 px-2 py-1 border border-gray-300 rounded text-sm"
              />
            ) : (
              <span className="text-green-700">{content.correction}</span>
            )}
          </div>
        )}

        {content.explanation && (
          <div>
            <span className="font-medium text-gray-700">Explanation: </span>
            {isEditing ? (
              <textarea
                value={content.explanation}
                onChange={(e) => setEditedContent({ ...editedContent, explanation: e.target.value })}
                rows={2}
                className="w-full mt-1 px-2 py-1 border border-gray-300 rounded text-sm"
              />
            ) : (
              <span className="text-gray-600 italic">{content.explanation}</span>
            )}
          </div>
        )}

        {content.context && (
          <div className="text-gray-500 text-xs mt-2">
            Context: {content.context}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`border rounded-lg p-4 ${drill.visible_to_student ? "bg-green-50 border-green-200" : "bg-amber-50 border-amber-200"}`}>
      {/* Header */}
      <div className="flex items-start justify-between gap-2 mb-3">
        <div className="flex items-center gap-2 flex-wrap">
          <DrillTypeBadge type={drill.drill_type as "pronunciation" | "grammar" | "vocabulary" | "fluency"} />
          <AutoGeneratedBadge
            reviewed={drill.tutor_approved}
            source={drill.source as "auto_fluency" | "auto_grammar" | "auto_vocabulary"}
          />
          {drill.focus_area && (
            <span className="text-xs text-gray-500">
              {drill.focus_area}
            </span>
          )}
        </div>

        {!drill.visible_to_student && (
          <div className="flex items-center gap-1">
            {isEditing ? (
              <>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => {
                    setIsEditing(false);
                    setEditedContent(drill.content);
                  }}
                  disabled={isPending}
                >
                  Cancel
                </Button>
                <Button
                  size="sm"
                  onClick={handleSaveEdit}
                  disabled={isPending}
                >
                  Save
                </Button>
              </>
            ) : (
              <>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => setIsEditing(true)}
                  disabled={isPending}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="text-red-600 hover:text-red-700 hover:bg-red-50"
                  onClick={() => setShowDeleteConfirm(true)}
                  disabled={isPending}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </Button>
              </>
            )}
          </div>
        )}
      </div>

      {/* Content */}
      {renderContent()}

      {/* Actions */}
      {!drill.visible_to_student && !isEditing && (
        <div className="mt-4 pt-3 border-t border-amber-200">
          <Button
            size="sm"
            onClick={handleApprove}
            disabled={isPending}
            className="w-full"
          >
            {isPending ? "Approving..." : "Approve & Show to Student"}
          </Button>
        </div>
      )}

      {/* Delete Confirmation */}
      {showDeleteConfirm && (
        <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg">
          <p className="text-sm text-red-800 mb-2">Delete this drill? This cannot be undone.</p>
          <div className="flex gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={() => setShowDeleteConfirm(false)}
              disabled={isPending}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              variant="destructive"
              onClick={handleDelete}
              disabled={isPending}
            >
              {isPending ? "Deleting..." : "Delete"}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
