"use client";

import { useState, useTransition } from "react";
import { format } from "date-fns";
import { AutoGeneratedBadge } from "@/components/ui/auto-generated-badge";
import { DrillPreviewCard } from "./DrillPreviewCard";
import { Button } from "@/components/ui/button";
import {
  publishHomework,
  updateHomeworkDraft,
  discardHomeworkDraft,
  approveAllDrills,
} from "@/lib/actions/recording-review";

interface DrillPreview {
  id: string;
  content: Record<string, unknown>;
  drill_type: string;
  focus_area: string | null;
  source: string;
  visible_to_student: boolean;
  tutor_approved: boolean;
}

interface HomeworkDraftReviewPanelProps {
  homework: {
    id: string;
    title: string;
    instructions: string;
    status: string;
    source: string;
    recording_id: string | null;
    due_date: string | null;
    tutor_reviewed: boolean;
    created_at: string;
  };
  drills: DrillPreview[];
  aiSummary?: string | null;
  onUpdate?: () => void;
  studentName?: string;
}

export function HomeworkDraftReviewPanel({
  homework,
  drills,
  aiSummary,
  onUpdate,
  studentName,
}: HomeworkDraftReviewPanelProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedTitle, setEditedTitle] = useState(homework.title);
  const [editedInstructions, setEditedInstructions] = useState(homework.instructions);
  const [showDiscardConfirm, setShowDiscardConfirm] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [localDrills, setLocalDrills] = useState(drills);

  const pendingDrills = localDrills.filter((d) => !d.visible_to_student);
  const approvedDrills = localDrills.filter((d) => d.visible_to_student);

  const handlePublish = () => {
    startTransition(async () => {
      const result = await publishHomework(homework.id);
      if (result.success) {
        onUpdate?.();
      }
    });
  };

  const handleDiscard = () => {
    startTransition(async () => {
      const result = await discardHomeworkDraft(homework.id);
      if (result.success) {
        setShowDiscardConfirm(false);
        onUpdate?.();
      }
    });
  };

  const handleSaveEdits = () => {
    startTransition(async () => {
      const result = await updateHomeworkDraft(homework.id, {
        title: editedTitle,
        instructions: editedInstructions,
      });
      if (result.success) {
        setIsEditing(false);
        onUpdate?.();
      }
    });
  };

  const handleApproveAll = () => {
    if (!homework.recording_id) return;
    startTransition(async () => {
      const result = await approveAllDrills(homework.recording_id!);
      if (result.success) {
        setLocalDrills((prev) =>
          prev.map((d) => ({ ...d, visible_to_student: true, tutor_approved: true }))
        );
        onUpdate?.();
      }
    });
  };

  const handleDrillUpdate = () => {
    onUpdate?.();
  };

  return (
    <div className="border border-amber-300 rounded-lg bg-amber-50 overflow-hidden">
      {/* Header - Always visible */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full px-4 py-3 flex items-center justify-between hover:bg-amber-100 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-amber-200 rounded-full flex items-center justify-center">
            <svg className="w-4 h-4 text-amber-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
          </div>
          <div className="text-left">
            <div className="flex items-center gap-2">
              <span className="font-medium text-gray-900">{homework.title}</span>
              <AutoGeneratedBadge reviewed={false} source={homework.source as "auto_lesson_analysis"} />
            </div>
            <div className="text-sm text-gray-600">
              {studentName && <span>{studentName} · </span>}
              {localDrills.length} drill{localDrills.length !== 1 ? "s" : ""} generated
              {pendingDrills.length > 0 && (
                <span className="text-amber-700"> · {pendingDrills.length} pending review</span>
              )}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">
            {format(new Date(homework.created_at), "MMM d, h:mm a")}
          </span>
          <svg
            className={`w-5 h-5 text-gray-500 transition-transform ${isExpanded ? "rotate-180" : ""}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>

      {/* Expanded Content */}
      {isExpanded && (
        <div className="px-4 pb-4 border-t border-amber-200">
          {/* AI Summary */}
          {aiSummary && (
            <div className="mt-4 p-3 bg-white rounded-lg border border-gray-200">
              <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                <svg className="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
                AI Lesson Summary
              </h4>
              <div className="text-sm text-gray-600 whitespace-pre-wrap">
                {aiSummary.slice(0, 500)}
                {aiSummary.length > 500 && "..."}
              </div>
            </div>
          )}

          {/* Homework Details */}
          <div className="mt-4 p-3 bg-white rounded-lg border border-gray-200">
            <h4 className="text-sm font-medium text-gray-700 mb-2">Homework Details</h4>
            {isEditing ? (
              <div className="space-y-3">
                <div>
                  <label className="block text-xs text-gray-500 mb-1">Title</label>
                  <input
                    type="text"
                    value={editedTitle}
                    onChange={(e) => setEditedTitle(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500 mb-1">Instructions</label>
                  <textarea
                    value={editedInstructions}
                    onChange={(e) => setEditedInstructions(e.target.value)}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
                  />
                </div>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setIsEditing(false);
                      setEditedTitle(homework.title);
                      setEditedInstructions(homework.instructions);
                    }}
                    disabled={isPending}
                  >
                    Cancel
                  </Button>
                  <Button size="sm" onClick={handleSaveEdits} disabled={isPending}>
                    Save Changes
                  </Button>
                </div>
              </div>
            ) : (
              <div>
                <p className="text-sm text-gray-900 font-medium">{homework.title}</p>
                <p className="text-sm text-gray-600 mt-1">{homework.instructions}</p>
                <Button
                  size="sm"
                  variant="ghost"
                  className="mt-2"
                  onClick={() => setIsEditing(true)}
                >
                  Edit Details
                </Button>
              </div>
            )}
          </div>

          {/* Drills Section */}
          {localDrills.length > 0 && (
            <div className="mt-4">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-sm font-medium text-gray-700">
                  Generated Drills ({localDrills.length})
                </h4>
                {pendingDrills.length > 0 && (
                  <Button size="sm" variant="outline" onClick={handleApproveAll} disabled={isPending}>
                    Approve All ({pendingDrills.length})
                  </Button>
                )}
              </div>

              <div className="space-y-3">
                {localDrills.map((drill) => (
                  <DrillPreviewCard key={drill.id} drill={drill} onUpdate={handleDrillUpdate} />
                ))}
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="mt-6 flex flex-col sm:flex-row gap-3 pt-4 border-t border-amber-200">
            <Button
              onClick={handlePublish}
              disabled={isPending}
              className="flex-1"
            >
              {isPending ? "Publishing..." : "Publish to Student"}
            </Button>
            <Button
              variant="outline"
              onClick={() => setShowDiscardConfirm(true)}
              disabled={isPending}
              className="text-red-600 hover:bg-red-50 hover:border-red-300"
            >
              Discard Draft
            </Button>
          </div>

          {/* Discard Confirmation */}
          {showDiscardConfirm && (
            <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-800 mb-3">
                Are you sure you want to discard this homework and all associated drills?
                This cannot be undone.
              </p>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => setShowDiscardConfirm(false)}
                  disabled={isPending}
                >
                  Cancel
                </Button>
                <Button
                  size="sm"
                  variant="destructive"
                  onClick={handleDiscard}
                  disabled={isPending}
                >
                  {isPending ? "Discarding..." : "Yes, Discard"}
                </Button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
