import type { ToolLang } from "@/lib/tools/types";

export interface VocabWord {
  word: string;
  phonetic: string;
  partOfSpeech: string;
  level: "B1" | "B2" | "C1" | "C2";
  definition: string;          // In English (the interface language)
  nativeDefinition?: string;   // In the target language (for immersive learners)
  example: string;             // In the target language
  etymology: string;           // Word origin
  synonyms: string[];          // In target language
  antonyms: string[];          // In target language
  collocations: string[];
  quizOptions: string[];       // 4 definition options (English)
  correctOption: number;
}

// ─── ENGLISH ──────────────────────────────────────────────────────────────────
const EN_WORDS: VocabWord[] = [
  { word:"ameliorate", phonetic:"/əˈmiːlɪəreɪt/", partOfSpeech:"verb", level:"C1", definition:"To make something bad better; to improve.", example:"The new policy aims to ameliorate the conditions for low-income families.", etymology:"Latin 'meliorare' (to improve), from 'melior' (better).", synonyms:["improve","alleviate","remedy"], antonyms:["worsen","aggravate","exacerbate"], collocations:["ameliorate conditions","ameliorate suffering","ameliorate a situation"], quizOptions:["To make something bad better; to improve.","To make something worse.","To cancel formally.","To praise enthusiastically."], correctOption:0 },
  { word:"sanguine", phonetic:"/ˈsæŋɡwɪn/", partOfSpeech:"adjective", level:"C1", definition:"Optimistic, especially in a difficult situation.", example:"Despite the setbacks, she remained sanguine about the company's future.", etymology:"Latin 'sanguineus' (blood-red) — a ruddy complexion was thought to indicate cheerfulness.", synonyms:["optimistic","hopeful","upbeat"], antonyms:["pessimistic","despairing","gloomy"], collocations:["sanguine outlook","remain sanguine","feel sanguine about"], quizOptions:["Deeply anxious and troubled.","Optimistic, especially in a difficult situation.","Pale and lacking energy.","Excessively risk-averse."], correctOption:1 },
  { word:"laconic", phonetic:"/ləˈkɒnɪk/", partOfSpeech:"adjective", level:"C1", definition:"Using very few words; brief and concise in speech.", example:"His laconic reply — 'No' — ended the debate immediately.", etymology:"Greek 'Lakonikos' (of Sparta/Laconia), whose inhabitants were famed for saying little.", synonyms:["terse","brief","succinct","pithy"], antonyms:["verbose","long-winded","loquacious"], collocations:["laconic reply","laconic style","laconic wit"], quizOptions:["Extremely talkative and unable to stop speaking.","Prone to emotional outbursts.","Using very few words; brief and concise.","Showing excessive enthusiasm."], correctOption:2 },
  { word:"ephemeral", phonetic:"/ɪˈfemərəl/", partOfSpeech:"adjective", level:"B2", definition:"Lasting for a very short time.", example:"The beauty of cherry blossoms is enhanced by their ephemeral nature.", etymology:"Greek 'ephemeros' (lasting a day), from 'epi-' (on) + 'hemera' (day).", synonyms:["fleeting","transient","momentary"], antonyms:["permanent","lasting","enduring"], collocations:["ephemeral beauty","ephemeral fame","ephemeral pleasures"], quizOptions:["Lasting for a very long time.","Extremely bright and colourful.","Easily irritated.","Lasting for a very short time."], correctOption:3 },
  { word:"perspicacious", phonetic:"/ˌpɜːspɪˈkeɪʃəs/", partOfSpeech:"adjective", level:"C2", definition:"Having a ready insight; showing a clear, shrewd understanding.", example:"Her perspicacious analysis cut through the noise to identify the real problem.", etymology:"Latin 'perspicax' (sharp-sighted), from 'perspicere' (to see clearly through).", synonyms:["shrewd","astute","perceptive","discerning"], antonyms:["obtuse","dense","imperceptive"], collocations:["perspicacious observer","perspicacious remark","a perspicacious mind"], quizOptions:["Stubbornly refusing to change one's opinion.","Having a ready insight; shrewd.","Extremely nervous.","Favouring one group unfairly."], correctOption:1 },
  { word:"obfuscate", phonetic:"/ˈɒbfʌskeɪt/", partOfSpeech:"verb", level:"C1", definition:"To make something unclear, obscure, or confusing.", example:"The legal jargon seemed designed to obfuscate rather than clarify.", etymology:"Latin 'obfuscare', from 'ob-' (over) + 'fuscare' (to darken).", synonyms:["obscure","confuse","muddle","cloud"], antonyms:["clarify","illuminate","elucidate"], collocations:["obfuscate the truth","obfuscate the issue","deliberate obfuscation"], quizOptions:["To make perfectly clear.","To make unclear or confusing.","To record officially.","To strongly disagree with."], correctOption:1 },
  { word:"garrulous", phonetic:"/ˈɡærʊləs/", partOfSpeech:"adjective", level:"C1", definition:"Excessively talkative, especially about trivial matters.", example:"The garrulous taxi driver talked about football for the entire journey.", etymology:"Latin 'garrulus', from 'garrire' (to chatter).", synonyms:["talkative","loquacious","verbose"], antonyms:["taciturn","reserved","laconic"], collocations:["garrulous companion","garrulous nature"], quizOptions:["Stubbornly refusing to speak.","Excessively talkative about trivial matters.","Extremely shy.","Speaking in a stiff manner."], correctOption:1 },
  { word:"mercurial", phonetic:"/mɜːˈkjʊərɪəl/", partOfSpeech:"adjective", level:"C1", definition:"Subject to sudden or unpredictable changes of mood or mind.", example:"Her mercurial temperament kept her colleagues constantly on edge.", etymology:"Latin 'Mercurialis' (of Mercury), the Roman god of speed and change.", synonyms:["volatile","unpredictable","capricious"], antonyms:["steady","stable","consistent"], collocations:["mercurial temperament","mercurial personality"], quizOptions:["Calm and consistent.","Subject to sudden unpredictable mood changes.","Extremely slow and methodical.","Passionately devoted."], correctOption:1 },
  { word:"cogent", phonetic:"/ˈkəʊdʒənt/", partOfSpeech:"adjective", level:"B2", definition:"Clear, logical, and convincing.", example:"She made a cogent argument for reforming the tax system.", etymology:"Latin 'cogens' (driving together), from 'cogere' (to compel).", synonyms:["convincing","compelling","persuasive","logical"], antonyms:["weak","illogical","unconvincing"], collocations:["cogent argument","cogent reasoning","cogent explanation"], quizOptions:["Complex and hard to follow.","Clear, logical, and convincing.","Aggressively opposed.","Vague and poorly reasoned."], correctOption:1 },
  { word:"propitious", phonetic:"/prəˈpɪʃəs/", partOfSpeech:"adjective", level:"C1", definition:"Giving or indicating a good chance of success; favourable.", example:"The calm weather made for a propitious start to the expedition.", etymology:"Latin 'propitius' (favourable), from 'pro-' + 'petere' (to seek).", synonyms:["favourable","auspicious","promising"], antonyms:["inauspicious","unfavourable","ominous"], collocations:["propitious moment","propitious circumstances","a propitious sign"], quizOptions:["Threatening danger.","Excessively proud.","Giving a good chance of success; favourable.","Moving very slowly."], correctOption:2 },
];

// ─── SPANISH ──────────────────────────────────────────────────────────────────
const ES_WORDS: VocabWord[] = [
  { word:"anhelar", phonetic:"/a.ne'lar/", partOfSpeech:"verbo", level:"B2", definition:"To long for; to yearn for something deeply.", nativeDefinition:"Desear vehementemente algo.", example:"Anhela volver a su tierra natal después de tantos años.", etymology:"Del latín 'anhelare' (jadear, anhelar) — originalmente describía la respiración agitada del deseo.", synonyms:["desear","ansia","codiciar","apetecer"], antonyms:["rechazar","despreciar","aborrecer"], collocations:["anhelar la libertad","anhelar paz","anhelar el regreso"], quizOptions:["To dislike intensely.","To long for; to yearn for.","To pretend or feign.","To forget gradually."], correctOption:1 },
  { word:"efímero", phonetic:"/e.'fi.me.ɾo/", partOfSpeech:"adjetivo", level:"B2", definition:"Lasting a very short time; fleeting.", nativeDefinition:"Que dura muy poco tiempo.", example:"La fama efímera de los reality shows contrasta con el arte duradero.", etymology:"Del griego 'ephemeros' (de un día), de 'epi-' + 'hemera' (día).", synonyms:["fugaz","transitorio","pasajero","perecedero"], antonyms:["duradero","eterno","permanente"], collocations:["fama efímera","belleza efímera","éxito efímero"], quizOptions:["Lasting forever.","Lasting a very short time; fleeting.","Very loud and noticeable.","Extremely complex."], correctOption:1 },
  { word:"desconcertar", phonetic:"/des.kon.θer.'tar/", partOfSpeech:"verbo", level:"B2", definition:"To perplex or confuse someone; to disconcert.", nativeDefinition:"Perturbar o confundir a alguien.", example:"Su pregunta me desconcertó tanto que no supe qué responder.", etymology:"De 'des-' (negación) + 'concertar' (poner de acuerdo), del latín 'concertare'.", synonyms:["confundir","perturbar","desorientar","desconcertar"], antonyms:["tranquilizar","orientar","aclarar"], collocations:["desconcertar al público","quedarse desconcertado","una pregunta desconcertante"], quizOptions:["To encourage and motivate.","To perplex or confuse; to disconcert.","To organize efficiently.","To describe in detail."], correctOption:1 },
  { word:"tenaz", phonetic:"/te.'naθ/", partOfSpeech:"adjetivo", level:"B2", definition:"Tenacious; persistent; not giving up easily.", nativeDefinition:"Que persiste con fuerza en sus propósitos.", example:"Gracias a su carácter tenaz, logró superar todos los obstáculos.", etymology:"Del latín 'tenax' (que agarra), de 'tenere' (sostener).", synonyms:["perseverante","obstinado","constante","persistente"], antonyms:["débil","inconstante","voluble"], collocations:["carácter tenaz","defensa tenaz","lucha tenaz"], quizOptions:["Easily distracted.","Tenacious; persistent; not giving up easily.","Highly intelligent.","Frequently changing opinions."], correctOption:1 },
  { word:"pulcro", phonetic:"/.'pul.kɾo/", partOfSpeech:"adjetivo", level:"C1", definition:"Neat, clean, and tidy in appearance.", nativeDefinition:"Aseado, limpio y esmerado.", example:"Su presentación fue pulcra y profesional, impresionando a todos.", etymology:"Del latín 'pulcher' (bello, elegante).", synonyms:["aseado","impecable","esmerado","limpio"], antonyms:["descuidado","desaseado","sucio"], collocations:["aspecto pulcro","presentación pulcra","estilo pulcro"], quizOptions:["Dirty and disorganised.","Neat, clean, and tidy in appearance.","Extremely loud.","Deeply thoughtful."], correctOption:1 },
  { word:"perspicaz", phonetic:"/peɾ.spi.'kaθ/", partOfSpeech:"adjetivo", level:"C1", definition:"Shrewd; having sharp insight and good judgment.", nativeDefinition:"De penetrante agudeza de ingenio.", example:"La analista perspicaz identificó el problema en segundos.", etymology:"Del latín 'perspicax' (de visión aguda), de 'perspicere' (ver con claridad).", synonyms:["agudo","astuto","sagaz","lúcido"], antonyms:["torpe","obtuso","ingenuo"], collocations:["mente perspicaz","observador perspicaz","análisis perspicaz"], quizOptions:["Prone to exaggeration.","Shrewd; having sharp insight.","Extremely generous.","Slow to understand."], correctOption:1 },
  { word:"vehemente", phonetic:"/be.e.'men.te/", partOfSpeech:"adjetivo", level:"B2", definition:"Showing strong feeling; passionate and intense.", nativeDefinition:"Que actúa o se expresa con mucho ardor o pasión.", example:"Hizo una vehemente defensa de los derechos humanos ante el Parlamento.", etymology:"Del latín 'vehemens' (violento, apasionado).", synonyms:["apasionado","ardiente","fervoroso","intenso"], antonyms:["frío","apático","indiferente"], collocations:["defensa vehemente","protesta vehemente","discurso vehemente"], quizOptions:["Calm and indifferent.","Showing strong feeling; passionate and intense.","Slow and methodical.","Extremely cautious."], correctOption:1 },
  { word:"afable", phonetic:"/a.'fa.βle/", partOfSpeech:"adjetivo", level:"B2", definition:"Friendly, good-natured, and easy to talk to.", nativeDefinition:"Agradable en el trato y la conversación.", example:"La recepcionista afable nos hizo sentir bienvenidos de inmediato.", etymology:"Del latín 'affabilis', de 'ad-' + 'fari' (hablar).", synonyms:["amable","cordial","agradable","simpático"], antonyms:["hosco","antipático","brusco"], collocations:["persona afable","trato afable","carácter afable"], quizOptions:["Rude and unfriendly.","Friendly and easy to talk to.","Very quiet and reserved.","Highly ambitious."], correctOption:1 },
  { word:"estipular", phonetic:"/es.ti.pu.'lar/", partOfSpeech:"verbo", level:"C1", definition:"To specify as a requirement or condition; to stipulate.", nativeDefinition:"Establecer algo como condición en un acuerdo.", example:"El contrato estipula que el pago debe realizarse en 30 días.", etymology:"Del latín 'stipulari' (pedir garantías), quizás de 'stipula' (paja), usada en rituales de acuerdo.", synonyms:["especificar","establecer","acordar","fijar"], antonyms:["ignorar","omitir","eludir"], collocations:["estipular condiciones","el contrato estipula","según lo estipulado"], quizOptions:["To deny or refuse.","To specify as a requirement; to stipulate.","To celebrate an event.","To delay or postpone."], correctOption:1 },
  { word:"intransigente", phonetic:"/in.tɾan.si.'xen.te/", partOfSpeech:"adjetivo", level:"C1", definition:"Unwilling to compromise; inflexible and uncompromising.", nativeDefinition:"Que no admite transacciones ni término medio.", example:"Su postura intransigente impidió llegar a un acuerdo.", etymology:"De 'in-' (no) + 'transigir' (llegar a un acuerdo), del latín 'transigere'.", synonyms:["inflexible","rígido","obstinado","implacable"], antonyms:["flexible","tolerante","negociador"], collocations:["postura intransigente","actitud intransigente","negociador intransigente"], quizOptions:["Open to compromise.","Unwilling to compromise; inflexible.","Very creative.","Extremely patient."], correctOption:1 },
];

// ─── FRENCH ───────────────────────────────────────────────────────────────────
const FR_WORDS: VocabWord[] = [
  { word:"épanouir (s')", phonetic:"/e.pa.nwir/", partOfSpeech:"verbe pronominal", level:"B2", definition:"To blossom; to flourish; to reach full potential.", nativeDefinition:"S'ouvrir complètement, se développer pleinement.", example:"Elle s'est épanouie dans son nouveau poste de direction.", etymology:"De 'épanouir', de l'ancien français 'espanoir', du latin 'expandere' (étendre).", synonyms:["s'épanouir","fleurir","prospérer","se développer"], antonyms:["se flétrir","décliner","s'atrophier"], collocations:["s'épanouir dans son travail","une personnalité épanouie","épanouissement personnel"], quizOptions:["To wilt and decline.","To blossom; to flourish and develop fully.","To argue or debate.","To memorise something."], correctOption:1 },
  { word:"éphémère", phonetic:"/e.fe.mɛʁ/", partOfSpeech:"adjectif", level:"B2", definition:"Lasting only a very short time; fleeting.", nativeDefinition:"Qui ne dure que très peu de temps.", example:"La gloire éphémère des célébrités contraste avec l'œuvre des grands artistes.", etymology:"Du grec 'ephemeros' (d'un jour), de 'epi-' + 'hemera' (jour).", synonyms:["fugace","passager","transitoire","momentané"], antonyms:["durable","pérenne","éternel"], collocations:["gloire éphémère","beauté éphémère","mode éphémère"], quizOptions:["Extremely intense and overwhelming.","Lasting only a very short time; fleeting.","Happening regularly.","Deeply significant."], correctOption:1 },
  { word:"perspicace", phonetic:"/pɛʁ.spi.kas/", partOfSpeech:"adjectif", level:"C1", definition:"Having sharp insight; shrewd and perceptive.", nativeDefinition:"Qui a une vue pénétrante des choses.", example:"L'analyste perspicace avait prévu la crise bien avant les autres.", etymology:"Du latin 'perspicax' (à la vue perçante), de 'perspicere' (voir à travers).", synonyms:["clairvoyant","lucide","pénétrant","sagace"], antonyms:["obtus","naïf","aveugle"], collocations:["esprit perspicace","regard perspicace","observateur perspicace"], quizOptions:["Lacking good judgment.","Having sharp insight; shrewd and perceptive.","Very talkative.","Extremely ambitious."], correctOption:1 },
  { word:"bienveillant", phonetic:"/bjɛ̃.vɛ.jɑ̃/", partOfSpeech:"adjectif", level:"B2", definition:"Benevolent; kind and well-meaning towards others.", nativeDefinition:"Qui veut du bien, qui est animé d'une bonne volonté.", example:"Son regard bienveillant mit immédiatement les étudiants à l'aise.", etymology:"Du latin 'benevolens', de 'bene' (bien) + 'volens' (voulant).", synonyms:["bienveillant","aimable","attentionné","charitable"], antonyms:["malveillant","hostile","indifférent"], collocations:["regard bienveillant","attitude bienveillante","esprit bienveillant"], quizOptions:["Hostile and ill-intentioned.","Benevolent; kind and well-meaning.","Extremely ambitious.","Very strict and demanding."], correctOption:1 },
  { word:"ambivalent", phonetic:"/ɑ̃.bi.va.lɑ̃/", partOfSpeech:"adjectif", level:"C1", definition:"Having mixed or contradictory feelings about something.", nativeDefinition:"Qui présente deux valences opposées, des sentiments contradictoires.", example:"Il avait des sentiments ambivalents vis-à-vis de son départ à l'étranger.", etymology:"Du latin 'ambi-' (des deux côtés) + 'valens' (valant).", synonyms:["partagé","hésitant","contradictoire","indécis"], antonyms:["convaincu","déterminé","sans équivoque"], collocations:["sentiments ambivalents","attitude ambivalente","être ambivalent envers"], quizOptions:["Having a clear and certain opinion.","Having mixed or contradictory feelings.","Very enthusiastic about something.","Completely indifferent."], correctOption:1 },
  { word:"anodin", phonetic:"/a.nɔ.dɛ̃/", partOfSpeech:"adjectif", level:"B2", definition:"Harmless; trivial; having little significance.", nativeDefinition:"Qui est sans danger ni effet notable, sans importance.", example:"Ce qui semblait être une remarque anodine a provoqué une controverse.", etymology:"Du grec 'anodynos' (sans douleur), de 'an-' + 'odyne' (douleur).", synonyms:["banal","insignifiant","sans importance","inoffensif"], antonyms:["significatif","dangereux","important"], collocations:["remarque anodine","question anodine","air anodin"], quizOptions:["Very dangerous and threatening.","Harmless; trivial; of little significance.","Extremely complex.","Highly emotional."], correctOption:1 },
  { word:"nonchalant", phonetic:"/nɔ̃.ʃa.lɑ̃/", partOfSpeech:"adjectif", level:"C1", definition:"Casually calm and relaxed; showing a casual lack of concern.", nativeDefinition:"Qui agit avec une indifférence désinvolte.", example:"Il répondit d'un air nonchalant, comme si la question ne le concernait pas.", etymology:"De 'non-' + ancien français 'chaloir' (importer), du latin 'calere' (être chaud).", synonyms:["désinvolte","indifférent","détaché","impassible"], antonyms:["anxieux","préoccupé","tendu"], collocations:["air nonchalant","attitude nonchalante","ton nonchalant"], quizOptions:["Anxious and stressed.","Casually calm; showing a lack of concern.","Very enthusiastic.","Extremely organised."], correctOption:1 },
  { word:"flâner", phonetic:"/flɑ.ne/", partOfSpeech:"verbe", level:"B2", definition:"To stroll leisurely without any particular destination; to wander.", nativeDefinition:"Se promener sans but précis, en s'attardant.", example:"Nous avons flâné le long des Champs-Élysées pendant des heures.", etymology:"De l'ancien nordique 'flana' (courir ça et là) — un mot très parisien!", synonyms:["se promener","déambuler","errer","vagabonder"], antonyms:["se dépêcher","se presser","se hâter"], collocations:["flâner dans les rues","flâner au marché","un flâneur parisien"], quizOptions:["To rush from place to place.","To stroll leisurely without destination; to wander.","To argue loudly.","To plan carefully."], correctOption:1 },
  { word:"péremptoire", phonetic:"/pe.ʁɑ̃p.twaʁ/", partOfSpeech:"adjectif", level:"C1", definition:"Leaving no room for argument; final and authoritative.", nativeDefinition:"Qui tranche une question de manière absolue, sans appel.", example:"Son ton péremptoire n'admettait aucune réplique.", etymology:"Du latin 'peremptorius' (decisif), de 'perimere' (détruire, supprimer).", synonyms:["catégorique","définitif","tranchant","absolu"], antonyms:["nuancé","hésitant","ouvert au débat"], collocations:["ton péremptoire","décision péremptoire","air péremptoire"], quizOptions:["Open to debate and discussion.","Leaving no room for argument; final and authoritative.","Very gentle and soft.","Extremely modest."], correctOption:1 },
  { word:"déconcerter", phonetic:"/de.kɔ̃.sɛʁ.te/", partOfSpeech:"verbe", level:"B2", definition:"To perplex or unsettle someone; to disconcert.", nativeDefinition:"Troubler quelqu'un, le mettre dans l'embarras.", example:"Sa question inattendue déconcerta même les experts présents.", etymology:"De 'dé-' + 'concerter' (mettre en accord), du latin 'concertare'.", synonyms:["déconcerter","dérouter","troubler","désarçonner"], antonyms:["rassurer","tranquilliser","clarifier"], collocations:["déconcerter l'adversaire","être déconcerté par","une réaction déconcertante"], quizOptions:["To reassure and calm.","To perplex or unsettle; to disconcert.","To encourage strongly.","To plan in detail."], correctOption:1 },
];

// ─── GERMAN ───────────────────────────────────────────────────────────────────
const DE_WORDS: VocabWord[] = [
  { word:"Weltanschauung", phonetic:"/ˈvɛltʔanˌʃaʊ.ʊŋ/", partOfSpeech:"Substantiv (f)", level:"C1", definition:"A comprehensive worldview or philosophy of life.", nativeDefinition:"Eine umfassende Weltauffassung, Lebensphilosophie.", example:"Seine marxistische Weltanschauung prägte sein gesamtes Werk.", etymology:"Von 'Welt' (world) + 'Anschauung' (view, perception). Used internationally in English too.", synonyms:["Lebensphilosophie","Weltbild","Überzeugung"], antonyms:[], collocations:["eine Weltanschauung haben","marxistische Weltanschauung","religiöse Weltanschauung"], quizOptions:["A brief greeting.","A comprehensive worldview or philosophy of life.","A type of German bread.","A formal apology."], correctOption:1 },
  { word:"nachhaltig", phonetic:"/ˈnaːxˌhaltɪç/", partOfSpeech:"Adjektiv", level:"B2", definition:"Sustainable; having a lasting effect.", nativeDefinition:"Auf Dauer ausgerichtet; langfristige Wirkung habend.", example:"Das Unternehmen verfolgt eine nachhaltige Umweltstrategie.", etymology:"Von 'nachhalten' (to last, to persist) — literally 'holding on after'.", synonyms:["dauerhaft","langfristig","beständig"], antonyms:["kurzfristig","vergänglich","flüchtig"], collocations:["nachhaltige Entwicklung","nachhaltige Energie","nachhaltige Wirkung"], quizOptions:["Quick and temporary.","Sustainable; having a lasting effect.","Extremely expensive.","Very complicated."], correctOption:1 },
  { word:"eigenartig", phonetic:"/ˈaɪ̯ɡənˌʔaːɐ̯tɪç/", partOfSpeech:"Adjektiv", level:"B2", definition:"Strange, peculiar, or eccentric; characteristic of itself.", nativeDefinition:"Von besonderer, ungewöhnlicher Art.", example:"Er hatte eine eigenartige Angewohnheit, beim Denken laut zu summen.", etymology:"Von 'Eigenart' (peculiarity, characteristic), von 'eigen' (own, peculiar) + 'Art' (type, manner).", synonyms:["seltsam","merkwürdig","sonderbar","eigentümlich"], antonyms:["normal","gewöhnlich","typisch"], collocations:["eigenartiges Verhalten","eine eigenartige Person","eigenartig klingen"], quizOptions:["Completely normal.","Strange, peculiar, or eccentric.","Very beautiful.","Highly organised."], correctOption:1 },
  { word:"überwältigen", phonetic:"/ˌyːbɐˈvɛltɪɡən/", partOfSpeech:"Verb", level:"B2", definition:"To overwhelm; to overpower; to overcome with emotion or force.", nativeDefinition:"Jemanden oder etwas mit Gewalt oder Gefühlen überwältigen.", example:"Die Schönheit der Landschaft überwältigte uns alle.", etymology:"Von 'über-' (over) + 'wältigen' (to overcome), von 'walten' (to rule, to prevail).", synonyms:["bezwingen","besiegen","erschüttern"], antonyms:["sich behaupten","standhalten"], collocations:["von Emotionen überwältigt","einen Feind überwältigen","überwältigend schön"], quizOptions:["To ignore completely.","To overwhelm; to overpower with emotion or force.","To welcome warmly.","To plan carefully."], correctOption:1 },
  { word:"verschlechtern", phonetic:"/fɛɐ̯ˈʃlɛçtɐn/", partOfSpeech:"Verb", level:"B2", definition:"To worsen; to deteriorate; to make something worse.", nativeDefinition:"Schlechter machen oder werden.", example:"Die Lage verschlechterte sich trotz aller Bemühungen.", etymology:"Von 'ver-' (intensive prefix) + 'schlechter' (worse), von 'schlecht' (bad).", synonyms:["sich verschlechtern","verschlechtern","verschlimmern"], antonyms:["verbessern","aufbessern"], collocations:["die Lage verschlechtert sich","eine Situation verschlechtern","Gesundheit verschlechtert sich"], quizOptions:["To improve rapidly.","To worsen; to deteriorate.","To understand clearly.","To remain unchanged."], correctOption:1 },
  { word:"bescheiden", phonetic:"/bəˈʃaɪ̯dən/", partOfSpeech:"Adjektiv", level:"B2", definition:"Modest; not boastful or showy; humble.", nativeDefinition:"Nicht übermäßig anspruchsvoll; in seinen Wünschen und Ansprüchen zurückhaltend.", example:"Trotz seines Erfolgs blieb er immer bescheiden und zugänglich.", etymology:"Von 'bescheiden' (to inform, to apportion), ursprünglich 'wissend' — eine bescheidene Person weiß ihre Grenzen.", synonyms:["anspruchslos","demütig","schlicht","zurückhaltend"], antonyms:["arrogant","hochmütig","prahlerisch"], collocations:["bescheiden bleiben","bescheidene Anforderungen","eine bescheidene Persönlichkeit"], quizOptions:["Arrogant and boastful.","Modest; humble; not showy.","Extremely ambitious.","Very talkative."], correctOption:1 },
  { word:"zuversichtlich", phonetic:"/ˈtsuːfɐˌzɪçtlɪç/", partOfSpeech:"Adjektiv", level:"B2", definition:"Confident; optimistic; full of hope.", nativeDefinition:"Voller Zuversicht, guter Hoffnung.", example:"Sie war zuversichtlich, die Prüfung zu bestehen.", etymology:"Von 'Zuversicht' (confidence, hope), von 'zu' + 'Versicht' (view, prospect), ursprünglich 'looking forward to'.", synonyms:["optimistisch","hoffnungsvoll","positiv","selbstsicher"], antonyms:["pessimistisch","ängstlich","hoffnungslos"], collocations:["zuversichtlich sein","zuversichtlich stimmen","eine zuversichtliche Prognose"], quizOptions:["Pessimistic and hopeless.","Confident; optimistic; full of hope.","Angry and resentful.","Very busy and stressed."], correctOption:1 },
  { word:"unerbittlich", phonetic:"/ˌʊnʔɛɐ̯ˈbɪtlɪç/", partOfSpeech:"Adjektiv", level:"C1", definition:"Relentless; merciless; not to be deflected by entreaty.", nativeDefinition:"Keine Bitten oder Mitleid zulassend; gnadenlos.", example:"Der unerbittliche Druck der Konkurrenz zwang das Unternehmen zur Umstrukturierung.", etymology:"Von 'un-' + 'erbittlich' (entreatable), von 'erbitten' (to implore).", synonyms:["gnadenlos","unnachgiebig","erbarmungslos","kompromisslos"], antonyms:["nachsichtig","barmherzig","flexibel"], collocations:["unerbittliche Konkurrenz","unerbittlicher Druck","unerbittlich verfolgen"], quizOptions:["Kind and forgiving.","Relentless; merciless; not swayed by appeals.","Very slow and patient.","Extremely generous."], correctOption:1 },
  { word:"Fingerspitzengefühl", phonetic:"/ˈfɪŋɐˌʃpɪtsənɡəfyːl/", partOfSpeech:"Substantiv (n)", level:"C1", definition:"Tact; a fine sense of how to handle situations delicately.", nativeDefinition:"Feingefühl, besonderes Geschick im Umgang mit heiklen Situationen.", example:"In der Diplomatie ist Fingerspitzengefühl unerlässlich.", etymology:"Literally 'fingertip feeling' — the sensitivity to feel things precisely at your fingertips.", synonyms:["Taktgefühl","Feingefühl","Geschick","Sensibilität"], antonyms:["Taktlosigkeit","Grobheit"], collocations:["Fingerspitzengefühl beweisen","viel Fingerspitzengefühl brauchen","diplomatisches Fingerspitzengefühl"], quizOptions:["A type of German pastry.","Tact; a fine sense for handling delicate situations.","A fingerprint.","Extreme clumsiness."], correctOption:1 },
  { word:"zweideutig", phonetic:"/ˈtsvaɪ̯ˌdɔɪ̯tɪç/", partOfSpeech:"Adjektiv", level:"C1", definition:"Ambiguous; having two possible meanings, often with a double entendre.", nativeDefinition:"Doppeldeutig, zwei Deutungen zulassend.", example:"Seine zweideutige Antwort ließ alle im Unklaren.", etymology:"Von 'zwei' (two) + 'deutig' (meaning), von 'deuten' (to interpret, to mean).", synonyms:["doppeldeutig","mehrdeutig","unklar","vieldeutig"], antonyms:["eindeutig","klar","unmissverständlich"], collocations:["eine zweideutige Bemerkung","zweideutig formulieren","bewusst zweideutig"], quizOptions:["Perfectly clear and unambiguous.","Ambiguous; having two possible meanings.","Completely irrelevant.","Very detailed."], correctOption:1 },
];

export const ALL_VOCAB: Record<ToolLang, VocabWord[]> = {
  en: EN_WORDS,
  es: ES_WORDS,
  fr: FR_WORDS,
  de: DE_WORDS,
};

export function getDailyWord(lang: ToolLang): VocabWord {
  const bank = ALL_VOCAB[lang] ?? EN_WORDS;
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
  return bank[dayOfYear % bank.length];
}

export const VOCAB_META: Record<ToolLang, { title: string; dateLocale: string }> = {
  en: { title: "Word of the Day", dateLocale: "en-GB" },
  es: { title: "Palabra del Día", dateLocale: "es-ES" },
  fr: { title: "Mot du Jour", dateLocale: "fr-FR" },
  de: { title: "Wort des Tages", dateLocale: "de-DE" },
};
