// Progress types and constants - separated from server actions for Next.js compatibility
// "use server" files can only export async functions, so constants must live here

export type HomeworkStatus = "draft" | "assigned" | "in_progress" | "submitted" | "completed" | "cancelled";

export const HOMEWORK_STATUSES: HomeworkStatus[] = [
  "draft",
  "assigned",
  "in_progress",
  "submitted",
  "completed",
  "cancelled",
];

// ============================================================================
// Analytics
// ============================================================================

export type DemandSlot = {
  dayOfWeek: number;
  hourOfDay: number;
  bookingCount: number;
  demandLevel: "none" | "low" | "medium" | "high" | "very_high";
};

export type PeakTimeRecommendation = {
  dayOfWeek: number;
  hourOfDay: number;
  demandLevel: string;
  recommendation: string;
};

// ============================================================================
// AI Assistant
// ============================================================================

export interface AIConversation {
  id: string;
  user_id: string;
  user_role: "tutor" | "student";
  title: string | null;
  context_type: "general" | "lesson_prep" | "student_feedback" | "content_creation" | "scheduling" | null;
  is_active: boolean;
  message_count: number;
  created_at: string;
  updated_at: string;
}

export interface AIMessage {
  id: string;
  conversation_id: string;
  role: "user" | "assistant" | "system";
  content: string;
  metadata: Record<string, unknown>;
  tokens_used: number | null;
  created_at: string;
}

export interface AIUsage {
  id: string;
  user_id: string;
  month: string;
  total_tokens: number;
  total_requests: number;
  total_conversations: number;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// Copilot
// ============================================================================

export interface LessonBriefing {
  id: string;
  tutorId: string;
  studentId: string;
  bookingId: string;
  studentSummary: string | null;
  focusAreas: Array<{
    type: string;
    topic: string;
    reason: string;
    evidence: string;
    count?: number;
  }>;
  errorPatterns: Array<{
    type: string;
    count: number;
    examples: string[];
    severity: string;
    isL1Interference?: boolean;
  }>;
  suggestedActivities: Array<{
    title: string;
    description: string;
    durationMin: number;
    category: string;
    targetArea?: string;
  }>;
  srItemsDue: number;
  srItemsPreview: Array<{
    word: string;
    type: string;
    lastReviewed: string | null;
    repetitionCount: number;
  }>;
  goalProgress: {
    goalText: string;
    progressPct: number;
    targetDate: string | null;
    status: string;
  } | null;
  engagementTrend: "improving" | "stable" | "declining" | "new_student";
  engagementSignals: Array<{
    type: string;
    value: string | number;
    concern: boolean;
    description: string;
  }>;
  lessonsAnalyzed: number;
  lastLessonSummary: string | null;
  lastLessonDate: string | null;
  proficiencyLevel: string | null;
  nativeLanguage: string | null;
  targetLanguage: string | null;
  generatedAt: string;
  viewedAt: string | null;
  dismissedAt: string | null;
  student?: {
    id: string;
    fullName: string;
    email: string;
  };
  booking?: {
    id: string;
    scheduledAt: string;
    service?: {
      name: string;
      durationMinutes: number;
    };
  };
}

export interface PendingBriefingsResult {
  briefings: LessonBriefing[];
  count: number;
}

export interface CopilotSettings {
  enabled?: boolean;
  briefingsEnabled: boolean;
  briefingTiming?: string;
  briefingDelivery?: string;
  drillsEnabled?: boolean;
  summarizationEnabled?: boolean;
  defaultFocusAreas?: string[];
  minLessonsForBriefing?: number;
  autoGenerateHomework?: boolean;
  autoGenerateDrills?: boolean;
  engagementAlertsEnabled?: boolean;
  engagementAlertThresholdDays?: number;
}

// ============================================================================
// Drills
// ============================================================================

export type DrillType = "pronunciation" | "grammar" | "vocabulary" | "fluency";
export type DrillStatus = "pending" | "assigned" | "in_progress" | "completed";

export interface ScrambleData {
  words: string[];
  solution?: string[];
}

export interface MatchData {
  pairs: Array<{ id: string; left: string; right: string }>;
}

export interface GapFillData {
  sentence: string;
  answer: string;
  options: string[];
}

export interface DrillContent {
  type: "scramble" | "match" | "gap-fill";
  prompt?: string;
  data: ScrambleData | MatchData | GapFillData;
}

export interface LessonDrill {
  id: string;
  recording_id: string | null;
  student_id: string;
  tutor_id: string;
  booking_id: string | null;
  homework_assignment_id: string | null;
  content: DrillContent;
  drill_type: DrillType;
  status: DrillStatus;
  focus_area: string | null;
  due_date: string | null;
  is_completed: boolean;
  completed_at: string | null;
  created_at: string;
}

export interface DrillWithContext extends LessonDrill {
  tutor_name?: string;
  lesson_date?: string;
  homework_title?: string;
}

// ============================================================================
// Student Engagement
// ============================================================================

export type RiskStatus = "healthy" | "at_risk" | "critical" | "churned";

export type EngagementScore = {
  id: string;
  student_id: string;
  tutor_id: string;
  score: number;
  lesson_frequency_score: number;
  response_rate_score: number;
  homework_completion_score: number;
  practice_engagement_score: number;
  risk_status: RiskStatus;
  risk_status_override: RiskStatus | null;
  override_reason: string | null;
  override_at: string | null;
  override_by: string | null;
  days_since_last_lesson: number | null;
  days_since_last_message: number | null;
  last_computed_at: string;
  created_at: string;
  updated_at: string;
};

export type AtRiskStudent = {
  id: string;
  full_name: string;
  email: string;
  engagement_score: number;
  risk_status: RiskStatus;
  days_since_last_lesson: number | null;
  days_since_last_message: number | null;
  last_activity_at: string | null;
};

export type EngagementDashboard = {
  total_students: number;
  healthy_count: number;
  at_risk_count: number;
  critical_count: number;
  churned_count: number;
  average_score: number;
};
