import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { AutoGeneratedBadge, DrillTypeBadge } from "./auto-generated-badge";

const metaAuto: Meta<typeof AutoGeneratedBadge> = {
  title: "UI/AutoGeneratedBadge",
  component: AutoGeneratedBadge,
  tags: ["autodocs"],
};

export default metaAuto;
type Story = StoryObj<typeof AutoGeneratedBadge>;

export const NeedsReview: Story = {
  render: () => <AutoGeneratedBadge source="auto_lesson_analysis" />,
};

export const Reviewed: Story = {
  render: () => <AutoGeneratedBadge source="auto_lesson_analysis" reviewed />,
};

export const AllSources: Story = {
  render: () => (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_lesson_analysis" />
        <span className="text-sm text-muted-foreground">Lesson Analysis</span>
      </div>
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_ai_practice" />
        <span className="text-sm text-muted-foreground">AI Practice</span>
      </div>
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_fluency" />
        <span className="text-sm text-muted-foreground">Fluency Assessment</span>
      </div>
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_grammar" />
        <span className="text-sm text-muted-foreground">Grammar Check</span>
      </div>
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_vocabulary" />
        <span className="text-sm text-muted-foreground">Vocabulary</span>
      </div>
    </div>
  ),
};

export const Sizes: Story = {
  render: () => (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_grammar" size="sm" />
        <span className="text-sm text-muted-foreground">Small (default)</span>
      </div>
      <div className="flex items-center gap-2">
        <AutoGeneratedBadge source="auto_grammar" size="md" />
        <span className="text-sm text-muted-foreground">Medium</span>
      </div>
    </div>
  ),
};

export const ReviewedVsUnreviewed: Story = {
  render: () => (
    <div className="space-y-4">
      <div>
        <h4 className="text-sm font-medium mb-2">Needs Review</h4>
        <div className="flex gap-2 flex-wrap">
          <AutoGeneratedBadge source="auto_lesson_analysis" />
          <AutoGeneratedBadge source="auto_fluency" />
          <AutoGeneratedBadge source="auto_grammar" />
        </div>
      </div>
      <div>
        <h4 className="text-sm font-medium mb-2">Reviewed</h4>
        <div className="flex gap-2 flex-wrap">
          <AutoGeneratedBadge source="auto_lesson_analysis" reviewed />
          <AutoGeneratedBadge source="auto_fluency" reviewed />
          <AutoGeneratedBadge source="auto_grammar" reviewed />
        </div>
      </div>
    </div>
  ),
};

export const InContext: Story = {
  render: () => (
    <div className="p-4 border rounded-lg w-[400px] space-y-4">
      <div className="flex items-start justify-between">
        <div>
          <h3 className="font-medium">Lesson Summary</h3>
          <p className="text-sm text-muted-foreground">December 24, 2024</p>
        </div>
        <AutoGeneratedBadge source="auto_lesson_analysis" />
      </div>
      <p className="text-sm">
        Today we covered verb conjugation in the present tense. The student
        showed good understanding of regular -ar verbs but needs more practice
        with irregular verbs.
      </p>
    </div>
  ),
};

// DrillTypeBadge stories
export const DrillTypes: Story = {
  render: () => (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <DrillTypeBadge type="pronunciation" />
        <span className="text-sm text-muted-foreground">
          For speaking exercises
        </span>
      </div>
      <div className="flex items-center gap-2">
        <DrillTypeBadge type="grammar" />
        <span className="text-sm text-muted-foreground">
          For grammar practice
        </span>
      </div>
      <div className="flex items-center gap-2">
        <DrillTypeBadge type="vocabulary" />
        <span className="text-sm text-muted-foreground">
          For word learning
        </span>
      </div>
      <div className="flex items-center gap-2">
        <DrillTypeBadge type="fluency" />
        <span className="text-sm text-muted-foreground">
          For conversational flow
        </span>
      </div>
    </div>
  ),
};

export const DrillCard: Story = {
  render: () => (
    <div className="p-4 border rounded-lg w-[300px] space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="font-medium">Verb Conjugation</h3>
        <DrillTypeBadge type="grammar" />
      </div>
      <p className="text-sm text-muted-foreground">
        Practice conjugating regular -ar, -er, and -ir verbs in the present
        tense.
      </p>
      <div className="flex items-center justify-between text-xs text-muted-foreground">
        <span>10 questions</span>
        <span>~5 minutes</span>
      </div>
    </div>
  ),
};
