import { cn } from "@/lib/utils";

/**
 * Badge component for AI-generated content indicators.
 * Shows whether content was auto-generated and if it's been reviewed.
 *
 * @example
 * // Unreviewed AI content
 * <AutoGeneratedBadge source="auto_lesson_analysis" />
 *
 * @example
 * // Reviewed AI content
 * <AutoGeneratedBadge source="auto_grammar" reviewed />
 *
 * @example
 * // Larger size
 * <AutoGeneratedBadge source="auto_fluency" size="md" />
 */
interface AutoGeneratedBadgeProps {
  reviewed?: boolean;
  source?: "auto_lesson_analysis" | "auto_ai_practice" | "auto_fluency" | "auto_grammar" | "auto_vocabulary";
  className?: string;
  size?: "sm" | "md";
}

export function AutoGeneratedBadge({
  reviewed = false,
  source,
  className,
  size = "sm",
}: AutoGeneratedBadgeProps) {
  const sizeClasses = size === "sm" ? "text-xs px-2 py-0.5" : "text-sm px-2.5 py-1";

  // Determine the label based on source
  let sourceLabel = "AI";
  if (source === "auto_fluency") {
    sourceLabel = "Fluency";
  } else if (source === "auto_grammar") {
    sourceLabel = "Grammar";
  } else if (source === "auto_vocabulary") {
    sourceLabel = "Vocabulary";
  } else if (source === "auto_lesson_analysis") {
    sourceLabel = "Lesson AI";
  } else if (source === "auto_ai_practice") {
    sourceLabel = "Practice AI";
  }

  if (reviewed) {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 rounded-full font-medium",
          "bg-green-100 text-green-800",
          sizeClasses,
          className
        )}
      >
        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
          <path
            fillRule="evenodd"
            d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
            clipRule="evenodd"
          />
        </svg>
        {sourceLabel}
      </span>
    );
  }

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full font-medium",
        "bg-amber-100 text-amber-800",
        sizeClasses,
        className
      )}
    >
      <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
        <path
          fillRule="evenodd"
          d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z"
          clipRule="evenodd"
        />
      </svg>
      {sourceLabel} - Review
    </span>
  );
}

/**
 * Badge component for drill type categorization.
 * Color-coded by drill type for quick visual identification.
 *
 * @example
 * <DrillTypeBadge type="grammar" />
 * <DrillTypeBadge type="vocabulary" />
 * <DrillTypeBadge type="pronunciation" />
 * <DrillTypeBadge type="fluency" />
 */
interface DrillTypeBadgeProps {
  type: "pronunciation" | "grammar" | "vocabulary" | "fluency";
  className?: string;
}

export function DrillTypeBadge({ type, className }: DrillTypeBadgeProps) {
  const config = {
    pronunciation: { bg: "bg-blue-100", text: "text-blue-800", label: "Pronunciation" },
    grammar: { bg: "bg-purple-100", text: "text-purple-800", label: "Grammar" },
    vocabulary: { bg: "bg-green-100", text: "text-green-800", label: "Vocabulary" },
    fluency: { bg: "bg-orange-100", text: "text-orange-800", label: "Fluency" },
  };

  const { bg, text, label } = config[type] || config.pronunciation;

  return (
    <span
      className={cn(
        "inline-flex items-center text-xs px-2 py-0.5 rounded-full font-medium",
        bg,
        text,
        className
      )}
    >
      {label}
    </span>
  );
}
