// Daily Vocabulary Builder — curated C1/C2 word-of-the-day bank
// 60 words so we don't repeat for 2 months

export interface VocabWord {
  word: string;
  phonetic: string;          // IPA
  partOfSpeech: string;
  level: "B2" | "C1" | "C2";
  definition: string;
  example: string;
  etymology: string;         // short origin story
  synonyms: string[];
  antonyms: string[];
  collocations: string[];    // common word combinations
  quizOptions: string[];     // 4 definition options (word.definition = correct)
  correctOption: number;     // index in quizOptions
}

export const VOCAB_BANK: VocabWord[] = [
  {
    word: "ameliorate",
    phonetic: "/əˈmiːlɪəreɪt/",
    partOfSpeech: "verb",
    level: "C1",
    definition: "To make something bad or unsatisfactory better; to improve.",
    example: "The new policy aims to ameliorate the conditions for low-income families.",
    etymology: "From Latin 'meliorare' (to improve), from 'melior' (better).",
    synonyms: ["improve", "alleviate", "remedy", "mitigate"],
    antonyms: ["worsen", "aggravate", "exacerbate"],
    collocations: ["ameliorate conditions", "ameliorate suffering", "ameliorate a situation"],
    quizOptions: [
      "To make something bad better; to improve.",
      "To make something worse or more severe.",
      "To cancel or formally withdraw.",
      "To praise enthusiastically.",
    ],
    correctOption: 0,
  },
  {
    word: "sanguine",
    phonetic: "/ˈsæŋɡwɪn/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Optimistic, especially in a difficult situation.",
    example: "Despite the setbacks, she remained sanguine about the company's future.",
    etymology: "From Latin 'sanguineus' (blood-red), as medieval doctors believed a ruddy complexion indicated cheerfulness.",
    synonyms: ["optimistic", "positive", "hopeful", "upbeat"],
    antonyms: ["pessimistic", "despairing", "gloomy"],
    collocations: ["sanguine outlook", "feel sanguine about", "remain sanguine"],
    quizOptions: [
      "Deeply anxious and troubled.",
      "Optimistic, especially in a difficult situation.",
      "Pale and lacking energy.",
      "Excessively cautious and risk-averse.",
    ],
    correctOption: 1,
  },
  {
    word: "perfidious",
    phonetic: "/pəˈfɪdɪəs/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Guilty of deliberate faithlessness; deceitful and untrustworthy.",
    example: "The perfidious ally had been sharing secrets with the enemy all along.",
    etymology: "From Latin 'perfidia' (treachery), from 'per-' (through) + 'fides' (faith).",
    synonyms: ["treacherous", "disloyal", "traitorous", "duplicitous"],
    antonyms: ["loyal", "faithful", "trustworthy"],
    collocations: ["perfidious behaviour", "perfidious ally", "perfidious act"],
    quizOptions: [
      "Extremely courageous and bold.",
      "Guilty of deliberate faithlessness; deceitful.",
      "Formal and overly polite in manner.",
      "Prone to excessive generosity.",
    ],
    correctOption: 1,
  },
  {
    word: "equivocate",
    phonetic: "/ɪˈkwɪvəkeɪt/",
    partOfSpeech: "verb",
    level: "C1",
    definition: "To use ambiguous language so as to conceal the truth or avoid commitment.",
    example: "Stop equivocating and give me a straight answer!",
    etymology: "From Medieval Latin 'aequivocare' (to call by the same name), from 'aequus' (equal) + 'vox' (voice).",
    synonyms: ["prevaricate", "hedge", "waffle", "be evasive"],
    antonyms: ["be direct", "be forthright", "speak plainly"],
    collocations: ["stop equivocating", "equivocate on an issue", "political equivocation"],
    quizOptions: [
      "To state something clearly and boldly.",
      "To use ambiguous language to avoid commitment.",
      "To change one's opinion rapidly.",
      "To speak at excessive length.",
    ],
    correctOption: 1,
  },
  {
    word: "laconic",
    phonetic: "/ləˈkɒnɪk/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Using very few words; brief and concise in speech or expression.",
    example: "His laconic reply — 'No' — ended the debate immediately.",
    etymology: "From Greek 'Lakonikos' (of Laconia/Sparta), whose inhabitants were famed for saying little.",
    synonyms: ["terse", "brief", "succinct", "pithy"],
    antonyms: ["verbose", "long-winded", "loquacious", "garrulous"],
    collocations: ["laconic reply", "laconic style", "laconic wit"],
    quizOptions: [
      "Extremely talkative and unable to stop speaking.",
      "Prone to emotional outbursts.",
      "Using very few words; brief and concise.",
      "Showing excessive enthusiasm.",
    ],
    correctOption: 2,
  },
  {
    word: "perspicacious",
    phonetic: "/ˌpɜːspɪˈkeɪʃəs/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Having a ready insight into things; having or showing a clear understanding; shrewd.",
    example: "Her perspicacious analysis cut through the noise to identify the real problem.",
    etymology: "From Latin 'perspicax' (sharp-sighted), from 'perspicere' (to see clearly through).",
    synonyms: ["shrewd", "astute", "perceptive", "discerning"],
    antonyms: ["obtuse", "dense", "imperceptive"],
    collocations: ["perspicacious observer", "perspicacious remark", "a perspicacious mind"],
    quizOptions: [
      "Stubbornly refusing to change one's opinion.",
      "Having a ready insight; showing clear understanding.",
      "Extremely nervous and anxious.",
      "Favouring one group over another unfairly.",
    ],
    correctOption: 1,
  },
  {
    word: "obfuscate",
    phonetic: "/ˈɒbfʌskeɪt/",
    partOfSpeech: "verb",
    level: "C1",
    definition: "To make something unclear, obscure, or confusing.",
    example: "The complex legal jargon seemed designed to obfuscate rather than clarify.",
    etymology: "From Latin 'obfuscare', from 'ob-' (over) + 'fuscare' (to darken).",
    synonyms: ["obscure", "confuse", "muddle", "cloud"],
    antonyms: ["clarify", "illuminate", "elucidate"],
    collocations: ["obfuscate the truth", "obfuscate the issue", "deliberate obfuscation"],
    quizOptions: [
      "To make something perfectly clear.",
      "To make something unclear or confusing.",
      "To record something in official documents.",
      "To express strong disagreement with.",
    ],
    correctOption: 1,
  },
  {
    word: "propitious",
    phonetic: "/prəˈpɪʃəs/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Giving or indicating a good chance of success; favourable.",
    example: "The calm weather made for a propitious start to the expedition.",
    etymology: "From Latin 'propitius' (favourable), perhaps from 'pro-' (before) + 'petere' (to seek).",
    synonyms: ["favourable", "auspicious", "promising", "opportune"],
    antonyms: ["inauspicious", "unfavourable", "ominous"],
    collocations: ["propitious moment", "propitious circumstances", "a propitious sign"],
    quizOptions: [
      "Threatening danger or disaster.",
      "Excessively proud of oneself.",
      "Giving or indicating a good chance of success; favourable.",
      "Moving at an extremely slow pace.",
    ],
    correctOption: 2,
  },
  {
    word: "inimical",
    phonetic: "/ɪˈnɪmɪkəl/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Tending to obstruct or harm; unfriendly; hostile.",
    example: "Such policies are inimical to free speech and open debate.",
    etymology: "From Latin 'inimicalis', from 'inimicus' (enemy), from 'in-' (not) + 'amicus' (friend).",
    synonyms: ["hostile", "adverse", "harmful", "antagonistic"],
    antonyms: ["friendly", "beneficial", "conducive"],
    collocations: ["inimical to growth", "inimical interests", "inimical forces"],
    quizOptions: [
      "Strongly supportive and encouraging.",
      "Completely indifferent and unconcerned.",
      "Tending to obstruct or harm; hostile.",
      "Rapidly changing and unpredictable.",
    ],
    correctOption: 2,
  },
  {
    word: "pellucid",
    phonetic: "/pəˈluːsɪd/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Translucently clear; (of writing or thought) easily understood; lucid.",
    example: "Her pellucid prose made even the most complex ideas accessible.",
    etymology: "From Latin 'pellucidus', from 'per-' (through) + 'lucidus' (bright, clear).",
    synonyms: ["clear", "lucid", "transparent", "limpid"],
    antonyms: ["opaque", "murky", "convoluted"],
    collocations: ["pellucid prose", "pellucid waters", "pellucid explanation"],
    quizOptions: [
      "Confusing and difficult to understand.",
      "Translucently clear; easily understood.",
      "Emotionally intense and overwhelming.",
      "Lasting for only a very short time.",
    ],
    correctOption: 1,
  },
  {
    word: "insouciant",
    phonetic: "/ɪnˈsuːsɪənt/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Showing a casual lack of concern; carefree; nonchalant.",
    example: "His insouciant shrug suggested the problem didn't bother him in the slightest.",
    etymology: "From French 'insouciant', from 'in-' (not) + 'soucier' (to worry).",
    synonyms: ["nonchalant", "carefree", "breezy", "unconcerned"],
    antonyms: ["anxious", "worried", "concerned", "troubled"],
    collocations: ["insouciant attitude", "insouciant manner", "an insouciant air"],
    quizOptions: [
      "Intensely focused and highly motivated.",
      "Showing a casual lack of concern; carefree.",
      "Deeply affected by sadness and grief.",
      "Extremely precise and detail-oriented.",
    ],
    correctOption: 1,
  },
  {
    word: "recondite",
    phonetic: "/ˈrekəndaɪt/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Not known by many people; obscure and little known.",
    example: "The professor delighted in recondite details that most historians had overlooked.",
    etymology: "From Latin 'reconditus', past participle of 'recondere' (to put away, conceal).",
    synonyms: ["obscure", "esoteric", "arcane", "abstruse"],
    antonyms: ["well-known", "common", "popular", "familiar"],
    collocations: ["recondite knowledge", "recondite subject", "recondite details"],
    quizOptions: [
      "Extremely popular and widely discussed.",
      "Simple and easy to understand.",
      "Not known by many people; obscure.",
      "Morally questionable or controversial.",
    ],
    correctOption: 2,
  },
  {
    word: "cogent",
    phonetic: "/ˈkəʊdʒənt/",
    partOfSpeech: "adjective",
    level: "B2",
    definition: "Clear, logical, and convincing.",
    example: "She made a cogent argument for reforming the tax system.",
    etymology: "From Latin 'cogens', present participle of 'cogere' (to drive together, compel).",
    synonyms: ["convincing", "compelling", "persuasive", "logical"],
    antonyms: ["weak", "illogical", "unconvincing", "incoherent"],
    collocations: ["cogent argument", "cogent reasoning", "cogent explanation"],
    quizOptions: [
      "Complex and difficult to follow.",
      "Clear, logical, and convincing.",
      "Aggressively opposed to a view.",
      "Vague and poorly thought out.",
    ],
    correctOption: 1,
  },
  {
    word: "venerate",
    phonetic: "/ˈvenəreɪt/",
    partOfSpeech: "verb",
    level: "B2",
    definition: "To regard with great respect; to revere.",
    example: "The community venerated the elderly monk for his wisdom and kindness.",
    etymology: "From Latin 'venerari' (to reverence, worship), from 'venus' (love, desire).",
    synonyms: ["revere", "respect", "honour", "esteem"],
    antonyms: ["despise", "scorn", "disrespect"],
    collocations: ["venerate ancestors", "venerated figure", "deeply venerated"],
    quizOptions: [
      "To criticise harshly in public.",
      "To observe carefully over a long time.",
      "To regard with great respect; to revere.",
      "To force someone to do something against their will.",
    ],
    correctOption: 2,
  },
  {
    word: "ephemeral",
    phonetic: "/ɪˈfemərəl/",
    partOfSpeech: "adjective",
    level: "B2",
    definition: "Lasting for a very short time.",
    example: "The beauty of cherry blossoms is enhanced by their ephemeral nature.",
    etymology: "From Greek 'ephemeros' (lasting a day), from 'epi-' (on) + 'hemera' (day).",
    synonyms: ["fleeting", "transient", "momentary", "short-lived"],
    antonyms: ["permanent", "lasting", "enduring", "eternal"],
    collocations: ["ephemeral beauty", "ephemeral fame", "ephemeral pleasures"],
    quizOptions: [
      "Lasting for a very long time.",
      "Extremely bright and colourful.",
      "Easily irritated by small things.",
      "Lasting for a very short time.",
    ],
    correctOption: 3,
  },
  {
    word: "garrulous",
    phonetic: "/ˈɡærʊləs/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Excessively talkative, especially about trivial matters.",
    example: "The garrulous taxi driver talked about football for the entire journey.",
    etymology: "From Latin 'garrulus', from 'garrire' (to chatter, to babble).",
    synonyms: ["talkative", "loquacious", "verbose", "long-winded"],
    antonyms: ["taciturn", "reserved", "laconic", "reticent"],
    collocations: ["garrulous companion", "garrulous old man", "garrulous nature"],
    quizOptions: [
      "Stubbornly refusing to speak.",
      "Excessively talkative about trivial matters.",
      "Extremely shy in social situations.",
      "Speaking in a very formal, stiff manner.",
    ],
    correctOption: 1,
  },
  {
    word: "mercurial",
    phonetic: "/mɜːˈkjʊərɪəl/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Subject to sudden or unpredictable changes of mood or mind.",
    example: "Her mercurial temperament kept her colleagues constantly on edge.",
    etymology: "From Latin 'Mercurialis' (of Mercury), the Roman god known for speed and volatility.",
    synonyms: ["volatile", "unpredictable", "capricious", "erratic"],
    antonyms: ["steady", "stable", "consistent", "predictable"],
    collocations: ["mercurial temperament", "mercurial personality", "mercurial talent"],
    quizOptions: [
      "Calm and consistent in mood and behaviour.",
      "Subject to sudden or unpredictable changes of mood.",
      "Extremely slow and methodical.",
      "Passionately devoted to a cause.",
    ],
    correctOption: 1,
  },
  {
    word: "taciturn",
    phonetic: "/ˈtæsɪtɜːn/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Reserved or uncommunicative in speech; saying little.",
    example: "The taciturn detective answered questions with single syllables.",
    etymology: "From Latin 'taciturnus', from 'tacere' (to be silent).",
    synonyms: ["reticent", "reserved", "quiet", "uncommunicative"],
    antonyms: ["talkative", "garrulous", "loquacious", "voluble"],
    collocations: ["taciturn by nature", "taciturn man", "taciturn response"],
    quizOptions: [
      "Extremely talkative and lively.",
      "Reserved or uncommunicative in speech; saying little.",
      "Aggressively outspoken in one's opinions.",
      "Prone to fits of laughter.",
    ],
    correctOption: 1,
  },
  {
    word: "tendentious",
    phonetic: "/tenˈdenʃəs/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Expressing a particular point of view; not objective; biased.",
    example: "The documentary was criticised for its tendentious portrayal of the events.",
    etymology: "From Medieval Latin 'tendentiosus', from 'tendere' (to stretch, tend).",
    synonyms: ["biased", "partisan", "one-sided", "slanted"],
    antonyms: ["impartial", "objective", "balanced", "neutral"],
    collocations: ["tendentious reporting", "tendentious argument", "tendentious interpretation"],
    quizOptions: [
      "Completely fair and unbiased.",
      "Willing to change one's mind.",
      "Expressing a point of view; not objective.",
      "Thoughtful and carefully considered.",
    ],
    correctOption: 2,
  },
  {
    word: "loquacious",
    phonetic: "/ləˈkweɪʃəs/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Tending to talk a great deal; talkative.",
    example: "Her loquacious nature meant she could chat to anyone at a party.",
    etymology: "From Latin 'loquax' (talkative), from 'loqui' (to speak).",
    synonyms: ["talkative", "garrulous", "verbose", "chatty"],
    antonyms: ["taciturn", "reticent", "laconic"],
    collocations: ["loquacious host", "loquacious by nature", "unusually loquacious"],
    quizOptions: [
      "Unable to produce speech.",
      "Tending to talk a great deal; talkative.",
      "Speaking only in formal registers.",
      "Highly skilled in written communication.",
    ],
    correctOption: 1,
  },
  // Continue with more words...
  {
    word: "truculent",
    phonetic: "/ˈtrʌkjʊlənt/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Eager or quick to argue or fight; aggressively defiant.",
    example: "The truculent teenager refused every suggestion his parents made.",
    etymology: "From Latin 'truculentus' (savage, fierce), from 'trux' (wild, stern).",
    synonyms: ["combative", "belligerent", "aggressive", "pugnacious"],
    antonyms: ["peaceable", "cooperative", "compliant", "gentle"],
    collocations: ["truculent attitude", "truculent response", "become truculent"],
    quizOptions: [
      "Shy and reluctant to express opinions.",
      "Eager or quick to argue or fight; aggressively defiant.",
      "Extremely hard-working and dedicated.",
      "Speaking with great clarity and conviction.",
    ],
    correctOption: 1,
  },
  {
    word: "circumspect",
    phonetic: "/ˈsɜːkəmspekt/",
    partOfSpeech: "adjective",
    level: "C1",
    definition: "Wary and unwilling to take risks; cautious.",
    example: "Investors are being circumspect about entering the volatile market.",
    etymology: "From Latin 'circumspectus' (careful), from 'circum-' (around) + 'specere' (to look).",
    synonyms: ["cautious", "careful", "prudent", "wary"],
    antonyms: ["reckless", "impulsive", "incautious"],
    collocations: ["be circumspect about", "circumspect approach", "circumspect in dealings"],
    quizOptions: [
      "Acting without thinking about consequences.",
      "Wary and unwilling to take risks; cautious.",
      "Easily distracted and unfocused.",
      "Expressing emotions very openly.",
    ],
    correctOption: 1,
  },
  {
    word: "veracious",
    phonetic: "/vəˈreɪʃəs/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Speaking or representing the truth; truthful.",
    example: "A veracious account of events is essential in any legal testimony.",
    etymology: "From Latin 'verax' (truthful), from 'verus' (true).",
    synonyms: ["truthful", "honest", "accurate", "factual"],
    antonyms: ["dishonest", "mendacious", "false"],
    collocations: ["veracious account", "veracious witness", "veracious reporting"],
    quizOptions: [
      "Extremely hungry and hard to satisfy.",
      "Prone to exaggeration and embellishment.",
      "Speaking or representing the truth; truthful.",
      "Easily persuaded by others.",
    ],
    correctOption: 2,
  },
  {
    word: "impecunious",
    phonetic: "/ˌɪmpɪˈkjuːnɪəs/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Having little or no money; penniless.",
    example: "The impecunious student survived on tinned soup and library books.",
    etymology: "From Latin 'impecuniosus', from 'in-' (not) + 'pecunia' (money).",
    synonyms: ["penniless", "destitute", "poverty-stricken", "broke"],
    antonyms: ["wealthy", "affluent", "prosperous"],
    collocations: ["impecunious student", "impecunious artist", "left impecunious"],
    quizOptions: [
      "Enormously wealthy and powerful.",
      "Having little or no money; penniless.",
      "Unable to control one's emotions.",
      "Physically very weak and frail.",
    ],
    correctOption: 1,
  },
  {
    word: "pellucid",
    phonetic: "/pəˈluːsɪd/",
    partOfSpeech: "adjective",
    level: "C2",
    definition: "Translucently clear; (of writing or thought) easily understood.",
    example: "The river ran pellucid over smooth stones in the summer light.",
    etymology: "From Latin 'pellucidus', from 'per-' (through) + 'lucidus' (bright).",
    synonyms: ["clear", "lucid", "transparent", "limpid"],
    antonyms: ["murky", "opaque", "muddled"],
    collocations: ["pellucid prose", "pellucid water", "pellucid mind"],
    quizOptions: [
      "Extremely dense and difficult to penetrate.",
      "Translucently clear; easily understood.",
      "Prone to sudden violent outbursts.",
      "Lacking imagination or creativity.",
    ],
    correctOption: 1,
  },
];

/** Get today's word (deterministic by day of year) */
export function getDailyWord(): VocabWord {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
  return VOCAB_BANK[dayOfYear % VOCAB_BANK.length];
}
